CREATE OR REPLACE FUNCTION GetUserById(p_id INT)
RETURNS TABLE(id INT, login VARCHAR, password VARCHAR, name VARCHAR, surname VARCHAR, age INT) AS
$$
BEGIN
RETURN QUERY
SELECT *
FROM users u
WHERE u.Id = p_id;
END;
$$ LANGUAGE plpgsql;
