version: '3.9'

services:
  mongodb:
    image: mongo:8.0.3
    command: mongod --replSet replicaSet1
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"